In [61]:
import numpy as np
from functions import gradient
from functions import softmax
from functions import cross_entropy_error

## 工具类

In [89]:
def gradient(f,x,h=1e-6):
    x = np.array(x,dtype='float')
    g = np.zeros_like(x,dtype='float')
    x_line = x.reshape(-1,order='c')
    g_line = g.reshape(-1,order='c')
    for i in range(len(x_line)):
        tmp = x_line[i]
        x_line[i] = tmp + h
        y_high = f(x)
        x_line[i] = tmp - h
        y_low = f(x)
        x_line[i] = tmp
        g[i] = (y_high - y_low)/(2*h)
    return g

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

def cross_entropy_error(y,t,delta=1e-8):
    return - t.dot(np.log(y+delta))

## 构造一个W为2*3矩阵的神经网络

In [93]:
class SimpleNet:
    def predict(self,x,W):
        return x.dot(W)
    def loss(self,x,t,W):
        z = self.predict(x,W)
        y = softmax(z)
        loss_val = cross_entropy_error(y,t)
        print(z)
        print(y)
        print(t)
        print(loss_val)
        return loss_val

In [94]:
simpleNet = SimpleNet()

In [71]:
W = np.random.randn(2,3)

In [72]:
x = np.array([0.6,0.9])
t = np.array([0,0,1])

In [73]:
last_loss = simpleNet.loss(x,t,W)

In [95]:
eta = 1e-2
for i in range(1000):
    g = gradient(lambda W:simpleNet.loss(x,t,W),x)
    W -= eta * g

1.1700006
1.0
[0 0 1]
[-0.00000000e+00 -0.00000000e+00 -9.99999989e-09]
1.1699994
1.0
[0 0 1]
[-0.00000000e+00 -0.00000000e+00 -9.99999989e-09]


ValueError: setting an array element with a sequence.

In [ ]:
np.ze