In [11]:
import numpy as np

## 与门 或门 与非门

In [14]:
def and_gate(X):
    w1 = w2 = 1
    theta = 1
    return np.array(X[:,0]*w1 + X[:,1]*w2 > theta,dtype='int')

In [15]:
def or_gate(X):
    w1 = w2 = 1
    theta = 0
    return np.array(X[:,0]*w1 + X[:,1]*w2 > theta,dtype='int')

In [35]:
def nand_gate(X):
    w1 = w2 = -1
    theta = -2
    return np.array(X[:,0]*w1 + X[:,1]*w2 > theta,dtype='int')

In [16]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
y = and_gate(X)
print(y)

[1 0 0 0]


In [17]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
y = or_gate(X)
print(y)

[1 1 1 0]


In [36]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
y = nand_gate(X)
print(y)

[0 1 1 1]


## 异或门

In [39]:
def nor_gate(X):
    s1 = nand_gate(X)
    s2 = or_gate(X)
    s_output = np.hstack([s1.reshape(-1,1),s2.reshape(-1,1)])
    return and_gate(s_output)

In [40]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
y = nor_gate(X)
print(y)

[0 1 1 0]


NameError: name 's_output' is not defined